language: node_js
node_js:
  - "0.10"
  - "0.8"
matrix:
  include:
    - node_js: "0.10"
      env: TEST="all"
    - node_js: "0.8"
      env: TEST="node"

notifications:
  email:
    - jdemorais@linkedin.com
    - vbasavaraj@linkedin.com
    - jleppert@linkedin.com
    - jchan@linkedin.com
before_install:
  - npm install -g grunt-cli
script:
  - "[$TEST == 'all']  || grunt test"
  - "[$TEST == 'node'] || grunt testNode"